import { ReactElement } from "react";
import Navbar from "./navbar";

type LayoutProps = Required<{
  readonly children: ReactElement;
}>;

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <title>しまなび</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <Navbar />
      <main>{children}</main>
    </>
  );
}
